@baseUrl = http://localhost:3000

### GET root endpoint
GET {{baseUrl}}/

### GET posts
GET {{baseUrl}}/posts

### GET posts filtered, searched and sorted
GET {{baseUrl}}/posts?tag=dolci&search=torta&sortBy=title&order=desc

### 400 - Invalid sort field
GET {{baseUrl}}/posts?sortBy=date

### GET single post by ID
GET {{baseUrl}}/posts/1

### 400 - Invalid post ID
GET {{baseUrl}}/posts/abc

### 404 - Post not found
GET {{baseUrl}}/posts/999

### POST create new post
POST {{baseUrl}}/posts

### PUT update post by ID
PUT {{baseUrl}}/posts/1

### DELETE post by ID
DELETE {{baseUrl}}/posts/1

### 404
GET {{baseUrl}}/non-existent
